### ISSUE TITLE
Enable test in setup.py

### ISSUE THREAD

**Issue by vin0110** [vin0110/haas#41]

**Comment by vin0110** [comment]
Added code to support `python setup.py test`. However, the results are different than for straight unittest. That is:

```
python setup.py test
```
throws 8 errors
```
Ran 20 tests in 0.473s

FAILED (failures=8)
```

whereas 

```
python -m unittest discover tests
```

has no errors

```
Ran 20 tests in 1.650s

OK
```

**Comment by vin0110** [comment]
@oxhead please look at branch issue_41. It runs the test suite twice. The first time all tests succeed. On the second pass 9 fail. It appears that each failure is because the data base has info in it from the previous test run. Thus we can fix this by only running the test suite once or by resetting the DB. Maybe both need to be done. Please look at this.

Below is the output from setup.
```
$ python setup.py test                                                                                                                                                                  ✹
running test
running egg_info
writing haascli.egg-info/PKG-INFO
writing dependency_links to haascli.egg-info/dependency_links.txt
writing requirements to haascli.egg-info/requires.txt
writing top-level names to haascli.egg-info/top_level.txt
reading manifest file 'haascli.egg-info/SOURCES.txt'
writing manifest file 'haascli.egg-info/SOURCES.txt'
running build_ext
running test
running egg_info
writing haascli.egg-info/PKG-INFO
writing dependency_links to haascli.egg-info/dependency_links.txt
writing requirements to haascli.egg-info/requires.txt
writing top-level names to haascli.egg-info/top_level.txt
reading manifest file 'haascli.egg-info/SOURCES.txt'
writing manifest file 'haascli.egg-info/SOURCES.txt'
running build_ext
test_create_bad (test_stack_create.TestStackCreate) ... ok
test_create_with_file (test_stack_create.TestStackCreate) ... ok
test_create_with_file_absolute_path (test_stack_create.TestStackCreate) ... ok
test_create_with_nonfile (test_stack_create.TestStackCreate) ... ok
test_create_with_parameters (test_stack_create.TestStackCreate) ... ok
test_delete (test_stack_delete.TestStackDelete) ... ok
test_events (test_stack_events.TestStackEvents) ... ok
test_bad_argument (test_stack_list.TestStack) ... ok
test_list (test_stack_list.TestStackList) ... ok
test_list_empty (test_stack_list.TestStackList) ... ok
test_list_empty_long (test_stack_list.TestStackList) ... ok
test_list_filter_hit (test_stack_list.TestStackList) ... ok
test_list_long (test_stack_list.TestStackList) ... ok

----------------------------------------------------------------------
Ran 13 tests in 0.483s

OK
test_create_bad (test_stack_create.TestStackCreate) ... FAIL
test_create_with_file (test_stack_create.TestStackCreate) ... ok
test_create_with_file_absolute_path (test_stack_create.TestStackCreate) ... ok
test_create_with_nonfile (test_stack_create.TestStackCreate) ... FAIL
test_create_with_parameters (test_stack_create.TestStackCreate) ... ok
test_delete (test_stack_delete.TestStackDelete) ... FAIL
test_events (test_stack_events.TestStackEvents) ... ok
test_bad_argument (test_stack_list.TestStack) ... FAIL
test_list (test_stack_list.TestStackList) ... FAIL
test_list_empty (test_stack_list.TestStackList) ... FAIL
test_list_empty_long (test_stack_list.TestStackList) ... FAIL
test_list_filter_hit (test_stack_list.TestStackList) ... FAIL
test_list_long (test_stack_list.TestStackList) ... FAIL

======================================================================
FAIL: test_create_bad (test_stack_create.TestStackCreate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vin/Envs/haas/lib/python3.6/site-packages/moto/core/models.py", line 70, in wrapper
    result = func(*args, **kwargs)
  File "/Users/vin/Work/haas/tests/test_stack_create.py", line 41, in test_create_bad
    self.assertEqual(2, r.exit_code)
AssertionError: 2 != -1

======================================================================
FAIL: test_create_with_nonfile (test_stack_create.TestStackCreate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vin/Envs/haas/lib/python3.6/site-packages/moto/core/models.py", line 70, in wrapper
    result = func(*args, **kwargs)
  File "/Users/vin/Work/haas/tests/test_stack_create.py", line 114, in test_create_with_nonfile
    self.assertTrue('Aborted!' in r.output)
AssertionError: False is not true

======================================================================
FAIL: test_delete (test_stack_delete.TestStackDelete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vin/Envs/haas/lib/python3.6/site-packages/moto/core/models.py", line 70, in wrapper
    result = func(*args, **kwargs)
  File "/Users/vin/Work/haas/tests/test_stack_delete.py", line 43, in test_delete
    self.assertEqual(2, len(statuses))
AssertionError: 2 != 5

======================================================================
FAIL: test_bad_argument (test_stack_list.TestStack)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vin/Work/haas/tests/test_stack_list.py", line 22, in test_bad_argument
    self.assertEqual(2, r.exit_code)
AssertionError: 2 != -1

======================================================================
FAIL: test_list (test_stack_list.TestStackList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vin/Envs/haas/lib/python3.6/site-packages/moto/core/models.py", line 70, in wrapper
    result = func(*args, **kwargs)
  File "/Users/vin/Work/haas/tests/test_stack_list.py", line 54, in test_list
    self.assertEqual(2, len(statuses))
AssertionError: 2 != 5

======================================================================
FAIL: test_list_empty (test_stack_list.TestStackList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vin/Work/haas/tests/test_stack_list.py", line 77, in test_list_empty
    self.assertEqual(1, len(statuses))
AssertionError: 1 != 5

======================================================================
FAIL: test_list_empty_long (test_stack_list.TestStackList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vin/Work/haas/tests/test_stack_list.py", line 83, in test_list_empty_long
    self.assertEqual(1, len(statuses))
AssertionError: 1 != 15

======================================================================
FAIL: test_list_filter_hit (test_stack_list.TestStackList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vin/Work/haas/tests/test_stack_list.py", line 92, in test_list_filter_hit
    self.assertEqual(2, len(statuses))
AssertionError: 2 != 5

======================================================================
FAIL: test_list_long (test_stack_list.TestStackList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vin/Work/haas/tests/test_stack_list.py", line 65, in test_list_long
    self.assertEqual(6, len(statuses))
AssertionError: 6 != 15

----------------------------------------------------------------------
Ran 13 tests in 0.422s

FAILED (failures=9)
Test failed: <unittest.runner.TextTestResult run=13 errors=0 failures=9>
error: Test failed: <unittest.runner.TextTestResult run=13 errors=0 failures=9>
```
