### ISSUE TITLE
Don't know how to use cluster commands

### ISSUE THREAD

**Issue by vin0110** [vin0110/haas#63]
I get this follow error from cluster commands:

```
$  haas cluster -s onenode stop
Traceback (most recent call last):
  File "/Users/vin/Work/haas/haascli/utils.py", line 16, in __call__
    return cls.__instance
AttributeError: type object 'HaasConfigurationManager' has no attribute '_Singleton__instance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vin/Envs/haas/bin/haas", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/vin/Work/haas/bin/haas", line 13, in <module>
    sys.exit(main())
  File "/Users/vin/Work/haas/bin/haas", line 9, in main
    return haas.cli()
  File "/Users/vin/Envs/haas/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/vin/Envs/haas/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/vin/Envs/haas/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/vin/Envs/haas/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/vin/Envs/haas/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/vin/Envs/haas/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/vin/Envs/haas/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/vin/Work/haas/haascli/cluster.py", line 82, in stop
    conf = HaasConfigurationManager().get(ctx.obj['config'])
  File "/Users/vin/Work/haas/haascli/utils.py", line 18, in __call__
    cls.__instance = super(Singleton, cls).__call__(*args, **kwargs)
  File "/Users/vin/Work/haas/haascli/config.py", line 68, in __init__
    self.reload()
  File "/Users/vin/Work/haas/haascli/config.py", line 105, in reload
    self.config_db[config_name] = HaaSConfiguration.load(config_path)
  File "/Users/vin/Work/haas/haascli/config.py", line 35, in load
    config = {HaasConfigurationKey[k.upper()]: v for k, v in config_raw.items()}
  File "/Users/vin/Work/haas/haascli/config.py", line 35, in <dictcomp>
    config = {HaasConfigurationKey[k.upper()]: v for k, v in config_raw.items()}
  File "/Users/vin/Envs/haas/lib/python3.6/enum.py", line 327, in __getitem__
    return cls._member_map_[name]
KeyError: 'TEMPLATE_URL'
```

**Comment by oxhead** [comment]
You will need to create a config file for now.  Later on, we have to use the default ssh key under ~/.ssh if the key file is not set.

Try to run this command first.
```
haas config new --ssh-key ~/.ssh/osr.pem mycluster
```

**Comment by oxhead** [comment]
@vin0110  has refactored our config system.  This is no longer be an issue.
